apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - postgres-service.yml
  - postgres-statefulset.yml
  - postgres-pvc.yml
  - postgres-pv.yml
  - postgres-secret.yml

